name: Weekly UFC Scraper

on:
  schedule:
    - cron: "0 11 * * 0" # Every Sunday at 11 AM UTC
  workflow_dispatch: # Allow manual runs

permissions:
  contents: write

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Ensures full history is fetched, important for rebase

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install Puppeteer
        run: npm install puppeteer

      - name: Run scraper
        run: node scrape.js

      - name: Generate articles.json
        run: node generate-articles.js

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      # *** ADD THIS NEW STEP HERE ***
      - name: Pull latest changes before commit
        run: git pull --rebase origin main
        # This command fetches any new commits from the remote 'main' branch
        # and reapplies your local changes (from scraper/generator) on top of them.
        # This resolves potential conflicts and allows for a clean push.

      - name: Commit and push updated files
        run: |
          git add fights.json articles.json
          # The 'git diff --staged --quiet ||' part ensures commit/push only happens if there are actual changes
          git diff --staged --quiet || (git commit -m "🤖 chore: Update fight card and articles" && git push)
